import { Poppins } from "next/font/google";

import UpperNav from "@/components/UpperNav/UpperNav";
import LowerNav from "@/components/LowerNav/LowerNav";
import Footer from "@/components/Footer/Footer";
import BreadCrumb from "@/components/BreadCrumb/BreadCrumb";


const poppins = Poppins({
 subsets : ['latin'],
weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
 display: "swap"
})

export const metadata = {
  title: "Ecobazar",
  description: "Generated by create next app",
};

export default function ShopLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}  antialiased`}
      >
       <main>
        <BreadCrumb></BreadCrumb>
          {children}
       </main>
      </body>
    </html>
  );
}
